name: Build Docker images

on: 
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
      
      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build . --file Dockerfile --tag acpr --build-arg FONT_AWESOME_KEY=${{ secrets.FONT_AWESOME_KEY }}

      - name: Tag Docker image
        uses:  actions/docker/tag@master
        with:
          args: acpr cooperaj/acpr

      - name: Architecture Tag (Latest)
        uses: actions/docker/cli@master
        with:
          args: tag cooperaj/acpr:latest cooperaj/acpr:amd64-alpine-latest

      - name: Architecture Tag (Git)
        uses: actions/docker/cli@master
        with:
          args: tag cooperaj/acpr:${IMAGE_REF} cooperaj/acpr:amd64-alpine-${IMAGE_REF}

  build-arm64v8:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1

      - name: Register multiarch build tooling
        uses: actions/docker/cli@master
        with:
          args: run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build . --file Dockerfile.arm64v8 --tag acpr --build-arg FONT_AWESOME_KEY=${{ secrets.FONT_AWESOME_KEY }}

      - name: Tag Docker image
        uses:  actions/docker/tag@master
        with:
          args: acpr cooperaj/acpr

      - name: Architecture Tag (Latest)
        uses: actions/docker/cli@master
        with:
          args: tag cooperaj/acpr:latest cooperaj/acpr:arm64v8-alpine-latest

      - name: Architecture Tag (Git)
        uses: actions/docker/cli@master
        with:
          args: tag cooperaj/acpr:${IMAGE_REF} cooperaj/acpr:arm64v8-alpine-${IMAGE_REF}