name: Build Docker images

on: 
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
      
      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build . --file Dockerfile --tag acpr --build-arg FONT_AWESOME_KEY=${{ secrets.FONT_AWESOME_KEY }}

      - name: Tag Docker image
        uses:  actions/docker/tag@master
        with:
          args: acpr cooperaj/acpr

  build-arm64v8:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build . --file Dockerfile.arm64v8 --tag acpr --build-arg FONT_AWESOME_KEY=${{ secrets.FONT_AWESOME_KEY }}

      - name: Tag Docker image
        uses:  actions/docker/tag@master
        with:
          args: acpr cooperaj/acpr