name: Build Docker images

on: 
  push:
    branches:
      - main

jobs:
  build-push-images:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            cooperaj/acpr
          labels: |
            org.opencontainers.image.title=acpr.dev website
            org.opencontainers.image.description=Standalone image for the acpr.dev contact point website.
            org.opencontainers.image.vendor=NetworkPie
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy-to-dokku:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: 'ssh://dokku@n8e.dev/acpr.dev'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}